### ISSUE TITLE
Unhandled exception when exporting

### ISSUE THREAD

**Issue by speccius** [LuigiBlood/sat_wave#17]
I am unable to use File > Export in version v0.5.1.0.
This error occurs:
![error](https://user-images.githubusercontent.com/50077694/64601811-8a0a8f80-d3b5-11e9-8ea3-6d474275496d.PNG)
Is there any other way of dumping the repository?
If not, this needs a fix quickly.
OS:Windows 8.1 Pro

`************** Exception Text **************
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at FolderSelect.FolderSelectDialog.ShowDialog(IntPtr hWndOwner)
   at SatellaWave.MainWindow.exportToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by LuigiBlood** [comment]
I think you need to get updates for .NET Framework.

**Comment by speccius** [comment]
Thank you!
